
package Formulários;

/**
 * @author Luiz Felipe e David Cavalcanti
 * Este é o formulario de Menu/principal.
 * é neste formulario onde o usuario escolherar a função a ser realizada. 
 */

import Classes.Dados;

public class frmMenu extends javax.swing.JFrame {

private int perfil;
private String senha;
private String usuario;
private Dados clsDados;

    public void setDados(Dados clsDados){
        this.clsDados=clsDados;
    }

    public void setUsuario(String usuario){
        this.usuario=usuario;
    }
    
    public void setSenha(String senha){
        this.senha=senha;
    }
    
    
    public void setPerfil(int perfil){
        this.perfil=perfil;
    }
    
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        Deskpainel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnGeren = new javax.swing.JMenu();
        mnGerenClientes = new javax.swing.JMenuItem();
        mnGerenProdutos = new javax.swing.JMenuItem();
        mnGerenUser = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnGerenAlterarSenha = new javax.swing.JMenuItem();
        mnGerenAlterarUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnGerenSair = new javax.swing.JMenuItem();
        mnFinan = new javax.swing.JMenu();
        mnFinanVendas = new javax.swing.JMenuItem();
        mnAjudaSelectd = new javax.swing.JMenu();
        mnAjudaSobre = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Deskpainel.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout DeskpainelLayout = new javax.swing.GroupLayout(Deskpainel);
        Deskpainel.setLayout(DeskpainelLayout);
        DeskpainelLayout.setHorizontalGroup(
            DeskpainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        DeskpainelLayout.setVerticalGroup(
            DeskpainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        mnGeren.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/pasta.png"))); // NOI18N
        mnGeren.setText("Gerenciamento");

        mnGerenClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/clientes.png"))); // NOI18N
        mnGerenClientes.setText("Clientes");
        mnGerenClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGerenClientesActionPerformed(evt);
            }
        });
        mnGeren.add(mnGerenClientes);

        mnGerenProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/comida.png"))); // NOI18N
        mnGerenProdutos.setText("Produtos");
        mnGerenProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGerenProdutosActionPerformed(evt);
            }
        });
        mnGeren.add(mnGerenProdutos);

        mnGerenUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/usuarios.png"))); // NOI18N
        mnGerenUser.setText("Usuarios");
        mnGerenUser.setToolTipText("");
        mnGerenUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGerenUserActionPerformed(evt);
            }
        });
        mnGeren.add(mnGerenUser);
        mnGeren.add(jSeparator1);

        mnGerenAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/alterar senha.png"))); // NOI18N
        mnGerenAlterarSenha.setText("Alterar Senha");
        mnGerenAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGerenAlterarSenhaActionPerformed(evt);
            }
        });
        mnGeren.add(mnGerenAlterarSenha);

        mnGerenAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/alterar usuario.png"))); // NOI18N
        mnGerenAlterarUsuario.setText("Alterar Usuario");
        mnGerenAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGerenAlterarUsuarioActionPerformed(evt);
            }
        });
        mnGeren.add(mnGerenAlterarUsuario);
        mnGeren.add(jSeparator2);

        mnGerenSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/sair.png"))); // NOI18N
        mnGerenSair.setText("Sair");
        mnGerenSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGerenSairActionPerformed(evt);
            }
        });
        mnGeren.add(mnGerenSair);

        jMenuBar1.add(mnGeren);

        mnFinan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/dinheiro.png"))); // NOI18N
        mnFinan.setText("Financeiro");

        mnFinanVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/pagamento.png"))); // NOI18N
        mnFinanVendas.setText("Nova Venda");
        mnFinanVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFinanVendasActionPerformed(evt);
            }
        });
        mnFinan.add(mnFinanVendas);

        jMenuBar1.add(mnFinan);

        mnAjudaSelectd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/ajuda.png"))); // NOI18N
        mnAjudaSelectd.setText("Ajuda");

        mnAjudaSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/sobre.png"))); // NOI18N
        mnAjudaSobre.setText("Sobre");
        mnAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAjudaSobreActionPerformed(evt);
            }
        });
        mnAjudaSelectd.add(mnAjudaSobre);

        jMenuBar1.add(mnAjudaSelectd);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Deskpainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Deskpainel)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnGerenUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerenUserActionPerformed
        // Codigo do botão usuarios da barra de menu.
        frmUsuarios fusuario=new frmUsuarios();
        fusuario.setDados(clsDados);    
        Deskpainel.add(fusuario);
        fusuario.show();
    }//GEN-LAST:event_mnGerenUserActionPerformed

    private void mnGerenProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerenProdutosActionPerformed
          // Codigo do botão produtos da barra de menu.
        frmProdutos fProdutos=new frmProdutos();
        fProdutos.setDados(clsDados);    
        Deskpainel.add(fProdutos);
        fProdutos.show();
    }//GEN-LAST:event_mnGerenProdutosActionPerformed

    private void mnGerenClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerenClientesActionPerformed
        // Codigo do botão clientes da barra de menu
        frmClientes fcClientes=new frmClientes();
        fcClientes.setDados(clsDados);    
        Deskpainel.add(fcClientes);
        fcClientes.show();
    }//GEN-LAST:event_mnGerenClientesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       if(perfil==2){
           mnGerenClientes.setEnabled(false);
           mnGerenProdutos.setEnabled(false);
           mnGerenUser.setEnabled(false);
           
       }
    }//GEN-LAST:event_formWindowOpened

    private void mnGerenSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerenSairActionPerformed
        //codigo do botão sair do formulario menu.
        clsDados.salvarTudo();
        System.exit(0);
        
    }//GEN-LAST:event_mnGerenSairActionPerformed

    private void mnGerenAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerenAlterarUsuarioActionPerformed
        // Codigo do botão alterar usuario:
        this.setVisible(false);
        FrmLogin mLogin= new FrmLogin();
        mLogin.setDados(clsDados);
        mLogin.setLocationRelativeTo(null);
        mLogin.setVisible(true);
    }//GEN-LAST:event_mnGerenAlterarUsuarioActionPerformed

    private void mnGerenAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerenAlterarSenhaActionPerformed
        //codigo do botão alterar senha.
        frmTrocarSenha mSenha= new frmTrocarSenha(this, rootPaneCheckingEnabled);
        mSenha.setLocationRelativeTo(null);
        mSenha.setSenha(senha);
        mSenha.setUsuario(usuario);
        mSenha.setDados(clsDados);
        mSenha.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnGerenAlterarSenhaActionPerformed

    private void mnAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAjudaSobreActionPerformed
        // Codigo do botão sobre.
        frmSobre mSobre= new frmSobre(this, rootPaneCheckingEnabled);
        mSobre.setLocationRelativeTo(this);
        mSobre.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnAjudaSobreActionPerformed

    private void mnFinanVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFinanVendasActionPerformed
        // Codigo do botão nova venda.
        frmFatura mFatura= new frmFatura();
        mFatura.setDados(clsDados);
        Deskpainel.add(mFatura);
        mFatura.show();

    }//GEN-LAST:event_mnFinanVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Deskpainel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnAjudaSelectd;
    private javax.swing.JMenuItem mnAjudaSobre;
    private javax.swing.JMenu mnFinan;
    private javax.swing.JMenuItem mnFinanVendas;
    private javax.swing.JMenu mnGeren;
    private javax.swing.JMenuItem mnGerenAlterarSenha;
    private javax.swing.JMenuItem mnGerenAlterarUsuario;
    private javax.swing.JMenuItem mnGerenClientes;
    private javax.swing.JMenuItem mnGerenProdutos;
    private javax.swing.JMenuItem mnGerenSair;
    private javax.swing.JMenuItem mnGerenUser;
    // End of variables declaration//GEN-END:variables
}
