
package Formulários;

import Classes.Dados;
import javax.swing.JOptionPane;


/**
 *@author luiz Felipe
 * Este é o formulario para alterar senha.
 * Nele pedimos que o usuario coloque a senha atual,nova senha e a confirme.
 * Temos então os códigos para verificar se os dados passados estão corretos e então realizar a mudança de senha.
 * 
 */
public class frmTrocarSenha extends javax.swing.JDialog {
    
    private String senha;
    private String usuario;
    private Dados clsDados;

    public void setDados(Dados clsDados){
        this.clsDados=clsDados;
    }
    

    public void setUsuario(String usuario){
        this.usuario=usuario;
    }
    
    public void setSenha(String senha){
        this.senha=senha;
    }
    
    public frmTrocarSenha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdSalvarSenha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtConfirmar = new javax.swing.JPasswordField();
        cmdSair = new javax.swing.JButton();
        txtAtual = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtNova = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trocar a Senha");
        setResizable(false);

        cmdSalvarSenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmdSalvarSenha.setForeground(new java.awt.Color(0, 102, 204));
        cmdSalvarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/file.png"))); // NOI18N
        cmdSalvarSenha.setText("Salvar");
        cmdSalvarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalvarSenhaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Senha Atual");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Confirmar Senha:");

        cmdSair.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmdSair.setForeground(new java.awt.Color(0, 102, 204));
        cmdSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/sair.png"))); // NOI18N
        cmdSair.setText("Sair");
        cmdSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSairActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Nova Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(cmdSalvarSenha)
                                .addGap(86, 86, 86)
                                .addComponent(cmdSair))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(txtNova, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSair)
                    .addComponent(cmdSalvarSenha))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSalvarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalvarSenhaActionPerformed
        // Codigo do botão Salvar senha.
        String atual=new String(txtAtual.getPassword());
        String nova=new String(txtNova.getPassword());
        String confirmar=new String(txtConfirmar.getPassword());
        
        if(atual.equals("")){
            JOptionPane.showMessageDialog(rootPane, "DIGITE A SENHA ATUAL");
            txtAtual.requestFocusInWindow();
            return;
        }
        if(nova.equals("")){
            JOptionPane.showMessageDialog(rootPane, "DIGITE A NOVA SENHA");
            txtNova.requestFocusInWindow();
            return;
        }
        
        if(confirmar.equals("")){
            JOptionPane.showMessageDialog(rootPane, "DIGITE A CONFIRMAÇÃO DA NOVA SENHA");
            txtConfirmar.requestFocusInWindow();
            return;
        }
        
        if(!atual.equals(senha)){
            JOptionPane.showMessageDialog(rootPane, "SENHA ATUAL NÃO CORRESPONDE COM A SENHA CADASTRADA");
            txtAtual.setText("");
            txtAtual.requestFocusInWindow();
            return;
        }
        
        if(!confirmar.equals(nova)){
            JOptionPane.showMessageDialog(rootPane, "AS SENHAS NÃO SÃO IGUAIS");
            txtNova.setText("");
            txtConfirmar.setText("");
            
            txtNova.requestFocusInWindow();
            return;
        }
        
        clsDados.trocarSenha(usuario, nova);
        JOptionPane.showMessageDialog(rootPane, "SENHA ALTERADA COM SUCESSO");
        this.dispose();

    }//GEN-LAST:event_cmdSalvarSenhaActionPerformed

    private void cmdSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSairActionPerformed
        // Codigo do botão sair.
        this.dispose();
    }//GEN-LAST:event_cmdSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmTrocarSenha dialog = new frmTrocarSenha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdSair;
    private javax.swing.JButton cmdSalvarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtAtual;
    private javax.swing.JPasswordField txtConfirmar;
    private javax.swing.JPasswordField txtNova;
    // End of variables declaration//GEN-END:variables
}
